package com.xxx.pai.mlp.man.documentcenter.infra.exception;

public enum DocumentErrorCode {
    INVALID_REQUEST("INVALID_REQUEST"),
    INVALID_NODE_NAME("INVALID_NODE_NAME"),
    INVALID_MOVE_TARGET("INVALID_MOVE_TARGET"),
    DIRECTORY_DEPTH_EXCEEDED("DIRECTORY_DEPTH_EXCEEDED"),
    DOCUMENT_NOT_FOUND("DOCUMENT_NOT_FOUND"),
    ASSET_NOT_FOUND("ASSET_NOT_FOUND"),
    DUPLICATE_DRAFT_NAME("DUPLICATE_DRAFT_NAME"),
    DUPLICATE_PUBLISHED_NAME("DUPLICATE_PUBLISHED_NAME"),
    DIRECTORY_NOT_EMPTY("DIRECTORY_NOT_EMPTY"),
    PUBLISHED_DOCUMENT_CANNOT_DELETE("PUBLISHED_DOCUMENT_CANNOT_DELETE"),
    ASSET_NOT_READY("ASSET_NOT_READY"),
    FILE_TOO_LARGE("FILE_TOO_LARGE"),
    CONTENT_TOO_LARGE("CONTENT_TOO_LARGE"),
    UNSUPPORTED_FILE_TYPE("UNSUPPORTED_FILE_TYPE"),
    CONTENT_SCHEMA_INVALID("CONTENT_SCHEMA_INVALID"),
    DOCUMENT_OPERATION_FAILED("DOCUMENT_OPERATION_FAILED"),
    OBJECT_STORAGE_UNAVAILABLE("OBJECT_STORAGE_UNAVAILABLE"),
    VALIDATION_FAILED("DOC_VALIDATION_FAILED"),
    NOT_FOUND("DOC_NOT_FOUND"),
    CONFLICT("DOC_CONFLICT"),
    DOCUMENT_VERSION_CONFLICT("DOCUMENT_VERSION_CONFLICT"),
    DOCUMENT_PUBLICATION_CONFLICT("DOCUMENT_PUBLICATION_CONFLICT"),
    TREE_VERSION_CONFLICT("TREE_VERSION_CONFLICT"),
    STORAGE_ERROR("DOC_STORAGE_ERROR"),
    INTERNAL_ERROR("DOC_INTERNAL_ERROR");

    private final String code;

    DocumentErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
